### PR TITLE
Add PHP8.4 support

### PR DESCRIPTION
**Pull request by NoiseByNorthwest**

### CODE REVIEW

**Comment by andypost** [comment]
Looks strange that clang on MacOS fails

**Comment by NoiseByNorthwest** [comment]
> Looks strange that clang on MacOS fails

Yes, but only with PHP8.4, @AlexNDRmac do you see what is the issue ? https://github.com/NoiseByNorthwest/php-spx/actions/runs/11092707280/job/30818091475?pr=270

**Comment by AlexNDRmac** [comment]
Looks like compile issue. As I know, php core team trying to move from C99 to smth like C++ standard. Redefinition warning should be resolved with #ifndef or forward declaration... but, it's php :)
I'll try to sort out with it locally on mac.

**Comment by NoiseByNorthwest** [comment]
> Looks like compile issue. As I know, php core team trying to move from C99 to smth like C++ standard. Redefinition warning should be resolved with #ifndef or forward declaration... but, it's php :)

Indeed, 8.4 introduces this dependency to C11+

```shell
✔ ~/dev/php-src [PHP-8.3 ↓·734|✔] 
23:09 $ ack 'typedef\s+struct\s+_zend_string\s+'
Zend/zend_types.h
96:typedef struct _zend_string     zend_string;
✔ ~/dev/php-src [PHP-8.3 ↓·734|✔] 
23:09 $ git co PHP-8.4
Switched to branch 'PHP-8.4'
Your branch is up to date with 'origin/PHP-8.4'.
✔ ~/dev/php-src [PHP-8.4|✔] 
23:09 $ ack 'typedef\s+struct\s+_zend_string\s+'
Zend/zend_map_ptr.h
24:typedef struct _zend_string zend_string;

Zend/zend_types.h
96:typedef struct _zend_string     zend_string;

Zend/zend_smart_str_public.h
22:typedef struct _zend_string zend_string;
```

**Comment by NoiseByNorthwest** [comment]
@AlexNDRmac fixed, I've just disabled "typedef-redefinition" warning on macOS.

**Comment by nhutnguyenvu** [comment]
always get like that for the latest/release branch
Configuring for:
PHP Api Version:         20220829
Zend Module Api No:      20220829
Zend Extension Api No:   420220829

**Comment by NoiseByNorthwest** [comment]
Because your PHP version seems to be 8.2

**Pull request merged**
