### PR TITLE
PHP 5.4 support

### LINKED ISSUE #226: PHP 5.4 support
I know that PHP 5.4 is not used by a lot of people nowadays and that I should probably migrate to a newer version, but would accept a PR that adds PHP 5.4 compatibility?

### PR DESCRIPTION
**Pull request by Athorcis**
Fixes #226

### CODE REVIEW

**Comment by NoiseByNorthwest** [comment]
Could you also update the other places where php5.6 is mentioned as the minimum supported version ?
AFAIK there are at least :
- the test matrix
- the README

**Comment by Athorcis** [comment]
I looked for the string 5.6 and I found as you mentioned that only the test matrix and the README needed to be updated

**Comment by NoiseByNorthwest** [comment]
@Athorcis it looks like the debian+PHP5.4&5.5 cannot succeed, maybe these PHP versions are not supported on this image ? Can you confirm it and exclude them from debian variant ?

**Comment by Athorcis** [comment]
@NoiseByNorthwest The problem is not Debian, but the repository https://packages.sury.org/php/ which doesn't support these versions. Should I exclude these versions from the Debian variant anyway ?

**Comment by NoiseByNorthwest** [comment]
@Athorcis Unless you know a workaround I think we should and that this is not a big issue.

**Pull request merged**
