### PR TITLE
Keep scroll position in flatprofile view on repaint

### LINKED ISSUE #266: highlighting a function in the flat profile jumps to the top of the list
Currently the `repaint` function invocation introduced at https://github.com/NoiseByNorthwest/php-spx/pull/126 causes a jump to the top of the flat profile view.

I think it makes sense to get the current scroll position via `document.querySelector('#flatprofile > div').scrollTop` and set it after everything is repainted.

### PR DESCRIPTION
**Pull request by DanielRuf**
Closes #266

### CODE REVIEW

**Comment by NoiseByNorthwest** [comment]
@DanielRuf LGTM, thanks :+1: 

Side note: the text is still unselected on repaint, but things are way better with your patch.

**Comment by DanielRuf** [comment]
> Side note: the text is still unselected on repaint

I will check this.

**Comment by DanielRuf** [comment]
When I click in the timeline view, the selected text on the left side is still selected:

image

@NoiseByNorthwest is this logic correct or should it automatically clear the selection on click in the timeline view at the top?

A simple "remove text selection" logic would be `window.getSelection().removeAllRanges()`.

**Comment by NoiseByNorthwest** [comment]
> When I click in the timeline view, the selected text on the left side is still selected:

I don't reproduce it, where do you click ? If I click on a span it makes than span selected (thus clearing the previously selected span info), if I click on elswhere (not an a span) it clears the overlay with the focus/selected span information...

**Comment by NoiseByNorthwest** [comment]
> Maybe creating a separate issue with the right steps to reproduce might be helpful.

Yes

> Otherwise if this is not a big issue and will be solved with the UI rrwrite, it might be not relevant at the moment.

Maybe, I let you decide

**Pull request merged**
